version: "3.9"
   
services:
  web:
    image: registry.digitalocean.com/dasam-docker-img/test
    working_dir: /app
    network_mode: 'host'
    command: "uvicorn app:app --port 8010 --host dasam.io"
