version: "3.9"
   
services:
  web:
    image: registry.digitalocean.com/dasam-docker-img/test
    volumes:
      - .:/app
    network_mode: 'host'
    command: "uvicorn app:app --reload --port 8010"
