name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
    MY_NAME: Available for all jobs in this workflow

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install doctl 
      run: |
        cd ~
        wget https://github.com/digitalocean/doctl/releases/download/v1.65.0/doctl-1.65.0-linux-amd64.tar.gz
        tar xf ~/doctl-1.65.0-linux-amd64.tar.gz
        sudo mv ~/doctl /usr/local/bin
    - name: Build the Docker image
      run: |
        doctl registry login --access-token "${{ secrets.REGISTRY_TOKEN }}"
        docker build . --file Dockerfile --tag registry.digitalocean.com/dasam-docker-img/test
        docker push registry.digitalocean.com/dasam-docker-img/test
        echo $(date)
        echo $MY_NAME
        echo $(which doctl)
    - name: Add the private SSH key to the ssh-agent
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
    - name: Build and deploy images on DigitalOcean
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        scp  -o StrictHostKeyChecking=no -r ./docker-compose.prod.yml dude@${{ secrets.VPS }}:~/app
        ssh -o StrictHostKeyChecking=no dude@${{ secrets.VPS }} << 'ENDSSH'
          cd ~/app
          docker pull registry.digitalocean.com/dasam-docker-img/test
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d
        ENDSSH
