name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

env:
  MY_NAME: ${{MY_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - run: echo I am echoing $MY_NAME
